#!name=B站去除会员购和游戏中心
#!desc=作者：循环1337

[MITM]
hostname = %APPEND% app.bilibili.com, grpc.biliapi.net, api.bilibili.com

[Body Rewrite]
# 1. 底部栏精简：剔除 pos 3 (发布) 和 pos 4 (会员购)
http-response-jq ^https:\/\/app\.bilibili\.com\/x\/resource\/show\/tab\/v2\? '.data.bottom |= map(select(.pos != 3 and .pos != 4))'

# 2. 顶部栏精简：直接将 top 数组重置为空 (彻底干掉游戏机、皮肤图标)
http-response-jq ^https:\/\/app\.bilibili\.com\/x\/resource\/show\/tab\/v2\? '.data.top = []'